sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t arzleyner/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arzleyner/react-test npm test

after_success:
  - docker build -t arzleyner/multi-client ./client
  - docker build -t arzleyner/multi-nginx ./nginx
  - docker build -t arzleyner/multi-server ./server
  - docker build -t arzleyner/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push arzleyner/multi-client
  - docker push arzleyner/multi-nginx
  - docker push arzleyner/multi-server
  - docker push arzleyner/multi-worker